### ISSUE TITLE
How to call the event?

### ISSUE THREAD

**Issue by Lama3L9R** [OtekCode/EventSystem#1]
i looked your code but i dont know how to call the event?or just can only use as one event?

**Comment by OtekCode** [comment]
https://github.com/OtekCode/EventSystem/blob/master/src/main/java/pl/otekplay/event/Invoker.java


You got annotation @EventMethod everything method with this annotation
after registerlIstener is "event"

All events need implement interface EventObject

You can invoke your event with method invokeObject(EventObject object)

wt., 7 sty 2020 o 10:08 Lama3L9R <notifications@github.com> napisał(a):

**Comment by Lama3L9R** [comment]
Thank you alot
